package fr.mwet.tools.assetcataloggenerator.renderer

import fr.mwet.tools.assetcataloggenerator.reader.AtlasRegionCatalogItem

fun renderTextureAssets(
    packageName: String,
    atlasPath: String,
    items: List<AtlasRegionCatalogItem>,
): String = buildString {
    val root = TextureAssetNode().also { root -> items.forEach { root.add(it) } }
    val textureAssetAliases = buildTextureAssetAliases(root, items)

    appendLine("package $packageName")
    appendLine()
    appendLine("import com.badlogic.gdx.assets.AssetDescriptor")
    appendLine("import com.badlogic.gdx.assets.AssetManager")
    appendLine("import com.badlogic.gdx.graphics.g2d.TextureAtlas")
    appendLine("import com.badlogic.gdx.graphics.g2d.TextureAtlas.AtlasRegion")
    appendLine("import com.badlogic.gdx.utils.Array")
    appendLine("import ktx.assets.getValue")
    appendLine("import ktx.assets.loadAsset")
    appendLine()
    appendLine("// Generated by asset-catalog-generator. Do not edit.")
    appendLine("open class TextureAssets(assetManager: AssetManager) {")
    appendLine("    protected val textureAtlas: TextureAtlas by assetManager.loadAsset(")
    appendLine("        AssetDescriptor(\"${atlasPath.escapeCharsForKotlinString()}\", TextureAtlas::class.java)")
    appendLine("    )")

    renderProperties(root, 1)
    renderTextureAssetAliases(textureAssetAliases, 1)
    renderNestedClasses(root, 1)

    appendLine("}")
}

private fun StringBuilder.renderClass(node: TextureAssetNode, indentLevel: Int) {
    val tabs = indent(indentLevel)
    appendLine("${tabs}inner class ${node.className} {")

    renderProperties(node, indentLevel + 1)
    renderRegions(node, indentLevel + 1)
    renderNestedClasses(node, indentLevel + 1)

    appendLine("${tabs}}")
}

private fun StringBuilder.renderProperties(node: TextureAssetNode, indentLevel: Int) {
    if (node.children.isEmpty()) return

    appendLine()
    val tabs = indent(indentLevel)
    node.children.values.forEach { child ->
        appendLine("${tabs}val ${child.propertyName}: ${child.className} by lazy { ${child.className}() }")
    }
}

private fun StringBuilder.renderTextureAssetAliases(aliases: List<TextureAssetAlias>, indentLevel: Int) {
    if (aliases.isEmpty()) return

    appendLine()
    val tabs = indent(indentLevel)
    aliases.forEach { alias ->
        val type = if (alias.isAnimation) "Array<AtlasRegion>" else "AtlasRegion"
        appendLine("${tabs}val ${alias.propertyName}: $type get() = ${alias.accessPath}")
    }
}

private fun StringBuilder.renderNestedClasses(node: TextureAssetNode, indentLevel: Int) {
    if (node.children.isEmpty()) return

    appendLine()
    renderChildClasses(node, indentLevel)
}

private fun StringBuilder.renderChildClasses(node: TextureAssetNode, indentLevel: Int) {
    node.children.values.forEachIndexed { index, child ->
        if (index > 0) appendLine()

        renderClass(child, indentLevel)
    }
}

private fun StringBuilder.renderRegions(node: TextureAssetNode, indentLevel: Int) {
    if (node.children.isNotEmpty() && node.regions.isNotEmpty()) {
        appendLine()
    }

    val tabs = indent(indentLevel)
    node.regions.forEach { region ->
        val finder = if (region.isAnimation) "findRegions" else "findRegion"
        val type = if (region.isAnimation) "Array<AtlasRegion>" else "AtlasRegion"

        appendLine("${tabs}val ${region.propertyName}: $type by lazy {")
        appendLine("$tabs    textureAtlas.$finder(${region.constantReference})")
        appendLine("${tabs}}")
    }
}
