package fr.mwet.tools.assetcataloggenerator.renderer

import fr.mwet.tools.assetcataloggenerator.reader.AssetCatalogItem
import kotlin.test.Test
import kotlin.test.assertEquals

class AssetCatalogRendererTest {
    @Test
    fun `renders root constants and nested groups`() {
        val root = assetCatalog(
            AssetCatalogItem(
                groups = emptyList(),
                name = "confirm",
                fullPath = "sounds/confirm.wav",
            ),
            AssetCatalogItem(
                groups = listOf("ui"),
                name = "click-sound",
                fullPath = "sounds/ui/click-sound.wav",
            ),
        )

        assertEquals(
            """
                |package test.assets
                |
                |// Generated by asset-catalog-generator. Do not edit.
                |object SoundAssets {
                |    const val Confirm: String = "sounds/confirm.wav"
                |
                |    object Ui {
                |        const val ClickSound: String = "sounds/ui/click-sound.wav"
                |    }
                |}
            """.asGeneratedFile(),
            renderAssetCatalog(
                packageName = "test.assets",
                objectName = "SoundAssets",
                root = root,
            ),
        )
    }

    @Test
    fun `renames colliding constants and skips exact duplicates`() {
        val root = assetCatalog(
            AssetCatalogItem(
                groups = emptyList(),
                name = "click",
                fullPath = "sounds/click.wav",
            ),
            AssetCatalogItem(
                groups = emptyList(),
                name = "click",
                fullPath = "sounds/click.wav",
            ),
            AssetCatalogItem(
                groups = emptyList(),
                name = "click",
                fullPath = "sounds/ui/click.wav",
            ),
        )

        assertEquals(
            """
                |package test.assets
                |
                |// Generated by asset-catalog-generator. Do not edit.
                |object SoundAssets {
                |    const val Click: String = "sounds/click.wav"
                |    const val Click2: String = "sounds/ui/click.wav"
                |}
            """.asGeneratedFile(),
            renderAssetCatalog(
                packageName = "test.assets",
                objectName = "SoundAssets",
                root = root,
            ),
        )
    }

    @Test
    fun `escapes generated string literals`() {
        val root = assetCatalog(
            AssetCatalogItem(
                groups = emptyList(),
                name = "odd",
                fullPath = "sounds/quote\"backslash\\name.wav",
            ),
        )

        assertEquals(
            """
                |package test.assets
                |
                |// Generated by asset-catalog-generator. Do not edit.
                |object SoundAssets {
                |    const val Odd: String = "sounds/quote\"backslash\\name.wav"
                |}
            """.asGeneratedFile(),
            renderAssetCatalog(
                packageName = "test.assets",
                objectName = "SoundAssets",
                root = root,
            ),
        )
    }

    private fun assetCatalog(vararg items: AssetCatalogItem): AssetCatalogNode =
        AssetCatalogNode().also { root ->
            items.forEach { item -> root.add(item) }
        }
}

private fun String.asGeneratedFile(): String = trimMargin().trimEnd() + "\n"
