package fr.mwet.tools.assetcataloggenerator

fun renderAssetCatalog(
    packageName: String,
    objectName: String,
    root: AssetCatalogNode,
): String = buildString {
    appendLine("package $packageName")
    appendLine()
    appendLine("// Generated by asset-catalog-generator. Do not edit.")
    appendLine("object $objectName {")
    renderAssetCatalogNode(root, indentLevel = 1)
    appendLine("}")
}

private fun StringBuilder.renderAssetCatalogNode(node: AssetCatalogNode, indentLevel: Int) {
    val tabs = indent(indentLevel)
    node.constants.forEach { (name, fullPath) ->
        appendLine("""${tabs}const val $name: String = "${fullPath.escapeCharsForKotlinString()}"""")
    }

    node.children.values.forEachIndexed { index, child ->
        if (node.constants.isNotEmpty() || index > 0) {
            appendLine()
        }
        appendLine("${tabs}object ${child.name} {")
        renderAssetCatalogNode(child, indentLevel + 1)
        appendLine("$tabs}")
    }
}

fun indent(level: Int): String = "    ".repeat(level)

fun String.escapeCharsForKotlinString(): String =
    buildString {
        this@escapeCharsForKotlinString.forEach { char ->
            when (char) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(char)
            }
        }
    }
